version: '3.0'

services:
  frontend:
    build: 
      context: src/frontend
      dockerfile: Dockerfile
      args:
        server_url: http://localhost:8081
    ports:
      - '8080:80'
    depends_on:
      - messages-api

  messages-api:
    build:
      context: src/backend
      dockerfile: FurAniJoGa.MessagesAPI/Dockerfile
    ports:
      - '8081:80'
    depends_on:
      - database

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
   
volumes:
  database:
    driver: local
    