version: '3.0'

services:
  frontend:

    build: 
      context: src/frontend
      dockerfile: Dockerfile

    ports:
      - '8080:80'
  backend:
    build:
      context: src/backend
      dockerfile: MessagesAPI/Dockerfile

    ports:
      - '80'
  rabbit-mq-relay:
    image: cloudamqp/websocket-tcp-relay
    ports:
      - '15670:15670'
    command:
      - '--upstream'
      - 'tcp://rabbit-mq:5672'
    depends_on:
      - rabbit-mq

  rabbit-mq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "8081:15672"
    